/**
 * API Client Layer
 * Central export for all API modules
 */

// Base client and utilities
export {
  apiRequest,
  get,
  post,
  put,
  patch,
  del,
  isSuccess,
  isError,
  unwrapResponse,
  buildQueryString,
  type ApiResponse,
  type ApiError,
  type ApiErrorCode,
  type RequestConfig,
} from './client';

// Progress API
export {
  completeAtom,
  completeLesson,
  updateStreak,
  useFreeze,
  getProgressByCourse,
  completeAtomSimple,
  isCourseComplete,
  getCourseProgressPercentage,
  type CompleteAtomRequest,
  type CompleteLessonRequest,
  type UpdateStreakRequest,
  type CompleteAtomResponse,
  type CompleteLessonResponse,
  type UpdateStreakResponse,
  type UseFreezeResponse,
  type CourseProgressData,
  type GetProgressByCourseResponse,
  type CelebrationData,
} from './progressApi';

// User API
export {
  createProfile,
  updateProfile,
  updatePreferences,
  getProfile,
  getCurrentUserProfile,
  updateSinglePreference,
  togglePreference,
  setLearningPace,
  setDailyGoal,
  completeOnboarding,
  updateAvatar,
  updateDisplayName,
  setLearningGoal,
  setExperienceLevel,
  hasCompletedOnboarding,
  getUserXP,
  getUserLevel,
  getUserStreak,
  type CreateProfileRequest,
  type UpdateProfileRequest,
  type UpdatePreferencesRequest,
  type CreateProfileResponse,
  type UpdateProfileResponse,
  type UpdatePreferencesResponse,
  type GetProfileResponse,
  type UserProfileData,
  type UserPreferencesData,
  type UserProgressData,
  type StreakDataResponse,
} from './userApi';

// Badge API
export {
  checkBadgeCriteria,
  getBadgeProgress,
  getAllBadges,
  getUserBadges,
  checkAndGetNewBadges,
  getSingleBadgeProgress,
  getAllBadgesWithProgress,
  getEarnedBadges,
  getUnearnedBadges,
  getBadgesNearCompletion,
  countEarnedBadges,
  hasBadge,
  getBadgeProgressPercent,
  createBadgeNotifications,
  formatBadgeEarnedMessage,
  getBadgeRarityColor,
  getBadgeRarityBgColor,
  type CheckBadgeCriteriaRequest,
  type GetBadgeProgressParams,
  type CheckBadgeCriteriaResponse,
  type GetBadgeProgressResponse,
  type GetAllBadgesResponse,
  type GetUserBadgesResponse,
  type EarnedBadge,
  type BadgeProgress,
  type BadgeProgressItem,
  type BadgeDefinition,
  type BadgeCriteria,
  type UserBadgeData,
  type BadgeNotification,
} from './badgeApi';
