'use client';

import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Download, FileText, Loader2, CheckCircle, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { cn } from '@/lib/utils';

export type ProgressReportData = {
  user: {
    name: string;
    email: string;
    joinedAt: string;
  };
  summary: {
    overallProgress: number;
    totalTimeSpent: number; // minutes
    lessonsCompleted: number;
    totalLessons: number;
    averageMastery: number;
    currentStreak: number;
    longestStreak: number;
  };
  skills: {
    mastered: Array<{
      name: string;
      mastery: number;
      masteredAt?: string;
    }>;
    inProgress: Array<{
      name: string;
      mastery: number;
      estimatedDays: number;
    }>;
    notStarted: Array<{
      name: string;
    }>;
  };
  predictions: {
    estimatedCompletionDate: string;
    predictedExamScore: number;
    readinessLevel: 'not_ready' | 'almost_ready' | 'ready' | 'highly_ready';
  };
  recentActivity: Array<{
    date: string;
    description: string;
    xpEarned: number;
  }>;
};

type ExportProgressReportProps = {
  data: ProgressReportData | null;
  isLoading?: boolean;
  onExport?: () => Promise<ProgressReportData | null | undefined>;
  className?: string;
};

type ExportStatus = 'idle' | 'loading' | 'success' | 'error';

export function ExportProgressReport({
  data,
  isLoading = false,
  onExport,
  className,
}: ExportProgressReportProps) {
  const [status, setStatus] = useState<ExportStatus>('idle');
  const [error, setError] = useState<string | null>(null);

  const formatDuration = (minutes: number): string => {
    if (minutes < 60) return `${minutes} min`;
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  };

  const getReadinessLabel = (level: string): string => {
    switch (level) {
      case 'highly_ready': return 'Highly Ready';
      case 'ready': return 'Ready';
      case 'almost_ready': return 'Almost Ready';
      default: return 'Not Ready';
    }
  };

  const generatePDFContent = useCallback((reportData: ProgressReportData): string => {
    const today = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    return `
APTLY LEARNING - PROGRESS REPORT
Generated: ${today}
=====================================

LEARNER INFORMATION
-------------------
Name: ${reportData.user.name}
Email: ${reportData.user.email}
Member Since: ${new Date(reportData.user.joinedAt).toLocaleDateString()}

PROGRESS SUMMARY
----------------
Overall Progress: ${reportData.summary.overallProgress}%
Total Time Spent: ${formatDuration(reportData.summary.totalTimeSpent)}
Lessons Completed: ${reportData.summary.lessonsCompleted}/${reportData.summary.totalLessons}
Average Mastery: ${Math.round(reportData.summary.averageMastery * 100)}%
Current Streak: ${reportData.summary.currentStreak} days
Longest Streak: ${reportData.summary.longestStreak} days

MASTERED SKILLS (${reportData.skills.mastered.length})
-----------------
${reportData.skills.mastered.map(s => `- ${s.name}: ${Math.round(s.mastery * 100)}%`).join('\n') || 'No skills mastered yet'}

SKILLS IN PROGRESS (${reportData.skills.inProgress.length})
-------------------
${reportData.skills.inProgress.map(s => `- ${s.name}: ${Math.round(s.mastery * 100)}% (~${s.estimatedDays} days to mastery)`).join('\n') || 'No skills in progress'}

SKILLS NOT STARTED (${reportData.skills.notStarted.length})
------------------
${reportData.skills.notStarted.map(s => `- ${s.name}`).join('\n') || 'All skills started!'}

PREDICTIONS
-----------
Estimated Completion: ${new Date(reportData.predictions.estimatedCompletionDate).toLocaleDateString()}
Predicted Exam Score: ${reportData.predictions.predictedExamScore}%
Readiness Level: ${getReadinessLabel(reportData.predictions.readinessLevel)}

RECENT ACTIVITY (Last 10)
-------------------------
${reportData.recentActivity.slice(0, 10).map(a => `${new Date(a.date).toLocaleDateString()} - ${a.description} (+${a.xpEarned} XP)`).join('\n') || 'No recent activity'}

=====================================
Report generated by Aptly Learning
https://aptlylearning.com
    `.trim();
  }, []);

  const handleExport = useCallback(async () => {
    setStatus('loading');
    setError(null);

    try {
      let reportData: ProgressReportData | null | undefined = data;

      // If onExport is provided, fetch fresh data
      if (onExport) {
        reportData = await onExport();
      }

      if (!reportData) {
        throw new Error('No report data available');
      }

      // Generate text content
      const content = generatePDFContent(reportData);

      // Create blob and download
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `aptly-progress-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      setStatus('success');

      // Reset status after 3 seconds
      setTimeout(() => setStatus('idle'), 3000);
    } catch (err) {
      console.error('Export error:', err);
      setError(err instanceof Error ? err.message : 'Failed to export report');
      setStatus('error');

      // Reset status after 3 seconds
      setTimeout(() => setStatus('idle'), 3000);
    }
  }, [data, onExport, generatePDFContent]);

  const getButtonContent = () => {
    switch (status) {
      case 'loading':
        return (
          <>
            <Loader2 className="animate-spin" size={18} />
            <span>Generating...</span>
          </>
        );
      case 'success':
        return (
          <>
            <CheckCircle size={18} />
            <span>Downloaded!</span>
          </>
        );
      case 'error':
        return (
          <>
            <AlertCircle size={18} />
            <span>Failed</span>
          </>
        );
      default:
        return (
          <>
            <Download size={18} />
            <span>Export Report</span>
          </>
        );
    }
  };

  const getButtonVariant = (): 'primary' | 'success' | 'danger' => {
    switch (status) {
      case 'success':
        return 'success';
      case 'error':
        return 'danger';
      default:
        return 'primary';
    }
  };

  return (
    <motion.div
      className={cn('flex flex-col gap-2', className)}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
    >
      <Button
        variant={getButtonVariant()}
        size="md"
        onClick={handleExport}
        isLoading={status === 'loading' || isLoading}
        isDisabled={status === 'loading' || isLoading || (!data && !onExport)}
        className="gap-2"
      >
        {getButtonContent()}
      </Button>

      {status === 'success' && (
        <motion.p
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-xs text-success text-center"
        >
          Report saved to Downloads
        </motion.p>
      )}

      {status === 'error' && error && (
        <motion.p
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-xs text-error text-center"
        >
          {error}
        </motion.p>
      )}
    </motion.div>
  );
}

// Preview component for the report
type ReportPreviewProps = {
  data: ProgressReportData;
  className?: string;
};

export function ReportPreview({ data, className }: ReportPreviewProps) {
  const formatDuration = (minutes: number): string => {
    if (minutes < 60) return `${minutes} min`;
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  };

  return (
    <div className={cn('bg-white rounded-lg border border-grey/20 p-4', className)}>
      <div className="flex items-center gap-2 mb-4">
        <FileText size={20} className="text-navy" />
        <h3 className="font-semibold text-navy">Report Preview</h3>
      </div>

      <div className="space-y-3 text-sm">
        <div className="grid grid-cols-2 gap-2">
          <div>
            <span className="text-grey">Progress</span>
            <p className="font-medium text-navy">{data.summary.overallProgress}%</p>
          </div>
          <div>
            <span className="text-grey">Time Spent</span>
            <p className="font-medium text-navy">{formatDuration(data.summary.totalTimeSpent)}</p>
          </div>
          <div>
            <span className="text-grey">Skills Mastered</span>
            <p className="font-medium text-navy">{data.skills.mastered.length}</p>
          </div>
          <div>
            <span className="text-grey">Current Streak</span>
            <p className="font-medium text-navy">{data.summary.currentStreak} days</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ExportProgressReport;
